export default {
  // Regex used for allowed app names and data keys
  NAME_REGEX: '[A-Za-z0-9][A-Za-z0-9_\\.]*',

  // Regex used for any object IDs generated by UDS
  UDS_ID_REGEX: '[A-Za-z0-9]+',

  UDS_PASSWORD_ID_REGEX: '[A-Za-z0-9$./]+',
};
