export default {
  // Regex used for allowed app names and data keys
  NAME_REGEX: '[A-Za-z0-9][A-Za-z0-9_\\.\\-]*',

  // Regex used to validate an incoming uuid generated by UDS
  UDS_UUID_REGEX: '[A-Za-f0-9]{8}-[A-Za-f0-9]{4}-[A-Za-f0-9]{4}-[0-9A-Za-f]{4}-[A-Za-f0-9]{12}',
};
