FORMAT: 1A

# Naming rules

The names of authorization modes, applications, as well as storage keys must be
of such a form as described by the regular expression `[A-Za-z0-9_\.]+`, and
they are case-sensitive.
