FORMAT: 1A

# API errors

The following is the list of errors that can be generated while validating the
call to any of the methods.

| Error                 | Description
|:---                   |:---
| `invalid_arg_name`    | One or more of the arguments passed to a method is not known.
| `missing_arg`         | One or more of the arguments required by a method was not passed.
