FORMAT: 1A

# Authentication errors

The following is the list of errors that can be generated while validating the
authentication of a method call.

| Error                 | Description                       |
|:---                   |:---                               |
| `not_authed`          | No authentication token provided. |
| `invalid_auth`        | Invalid authentication token.     |
