FORMAT: 1A

# Google Docs

[scenario source](https://hmhco.slack.com/files/U07CMCTU1/F6SHY9X08/user-centric-content.pdf)

We also want to increasingly support a set of external objects, for example a google docs file. In this context we don't want to store a copy of the google docs file, just the reference and metadata needed to connect that specific document to a user so they can manipulate it through Google API calls, etc. Effectively the concept that a document, URL, Youtube video, image, etc exists. It's expected that other services would use the user centric data service to maintain the inventory of these objects, but not that the user centric data service would provide the full interface to all these third party objects.

## Data Modeling

## Data Definition

## Data Manipulation
