FORMAT: 1A

# Arbitrary Text

[scenario source](https://hmhco.slack.com/files/U07CMCTU1/F6SHY9X08/user-centric-content.pdf)

We also increasingly want to be able to store arbitrary text blocks, which might be just like annotation without the link to the content. There is probably some line between small text blocks and large text blocks.

## Data Modeling

## Data Definition

## Data Manipulation
