FORMAT: 1A

# Examples

The following examples illustrate ways to combine method calls to create user
experiences.

## Data definition vs. manipulation

In all of the examples, we differentiate between the _data definition_ and
the _data manipulation_ stages.

_Data definition_ is the stage in which settings are created in the system. This
happens during the development of the systems that will consume the setting.
These operations are usually not triggered by end-user behavior. For instance:
in a SQL system, `CREATE TABLE` is considered a data definition command.

_Data manipulation_, on the other hand, is usually the operations that are
triggered as a result of some user action. For instance: in a SQL system,
`INSERT INTO` is considered a data manipulation command.

## List of examples

| Example                                   | Description
|---                                        |---
