FORMAT: 1A

# apps.setPerUserQuota

Sets the per-user storage quota on an existing app.

Decreasing the quota does not cause data to be deleted. In other words, if the
new value causes any users to be over the quota, their data will not be deleted,
but future write operations will fail.

:[](common-args.md url:"apps.setPerUserQuota" token:"Requires a service token.")

| Argument       | Example           | Required  | Description
|:---            |:---               |:---       |:---
| `name`         | `browser_client`  | Required  | The name of the app.
| `quota`        | `1024`            | Required  | The storage available to the app, per user, in bytes.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `invalid_name`            | `name` does not conform to the naming rules.
| `app_not_found`           | `name` does not name an existing app.
| `invalid_quota`           | `quota` is not a valid positive integer within max system quota limit.
