FORMAT: 1A

# data.user.delete

Delete data for a given user.

:[](common-args.md url:"data.user.delete" token:"Can be used with either a service token or a user token.")

| Argument      | Example               | Required  | Description
|:---           |:---                   |:---       |:---
| `key`         | `annotation_id123`    | Required  | A unique key to identify the data being stored.
| `requestor`   | `user_345`            | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`            | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error             | Description
|:---               |:---
| `not_authed`      | No authentication token provided.
| `invalid_auth`    | `requestor` does not have access to `owner` content.
| `invalid_key`     | `key` does not conform to the naming rules.
| `key_not_found`   | `key` does not describe an existing key for user.
| `invalid_user`    | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`  | Service token used and `requestor` not specified.
