FORMAT: 1A

# data.admin.apps

List apps for a given user.

:[](common-args.md url:"data.admin.apps" token:"Requires a service token.")

| Argument  | Example       | Required  | Description
|:---       |:---           |:---       |:---
| `user`    | `user_345`    | Required  | The target user to use when listing apps.

## Result

```javascript
{
    "ok": true,
    "result": [
      "app_1",
      "app_2"
    ]
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `not_authed`          | No authentication token provided.
| `wrong_token_type`    | This endpoint requires a service token.
| `invalid_user`        | `user` is not a valid user identifier.
