FORMAT: 1A

# data.app.set

Store a document for a given user.

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"data.app.set" token:"Can be used with either a service token or a user token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `key`         | `settings`                | Required  | A unique key to identify the data being stored.
| `data`        | `{"font-size": "12pt"}`   | Required  | The serialized JSON document to store.
| `app`         | `browser_client`          | Required  | The app storing data.
| `user`        | `user_345`                | Optional  | The user as which to set the data. Required if token type is service token.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `invalid_key`         | `key` does not conform to the naming rules.
| `name_in_use`         | `key` is already in use.
| `invalid_data`        | `data` is missing or not a serialized JSON document.
| `invalid_app`         | `app` does not conform to the naming rules.
| `app_not_found`       | `app` does not name an existing app.
| `invalid_user`        | `user` is not a valid user identifier.
| `user_not_found`      | User specified in `user` or user token was not found.
| `forbidden`           | Token is a user token, and user was specified and did not match.
| `quota_exceeded`      | The user does not have sufficient quota to store the data.
