FORMAT: 1A

# data.user.unshare

Unshare data for a given user.

:[](common-args.md url:"data.user.unshare" token:"Can be used with either a service token or a user token.")

| Argument      | Example           | Required  | Description
|:---           |:---               |:---       |:---
| `id`          | `z3Gh7pQ12z`      | Required  | The unique sharing ID.
| `requestor`   | `user_345`        | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`        | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `not_authed`          | No authentication token provided.
| `invalid_auth`        | `requestor` does not have access to `owner` content.
| `invalid_share_id`    | `id` does not conform to the naming rules.
| `share_id_not_found`  | `id` does not describe an existing sharing ID for user.
| `invalid_user`        | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`      | Service token used and `requestor` not specified.
