FORMAT: 1A

# data.app.list

List data for a given user.

:[](common-args.md url:"data.app.list" token:"Can be used with either a service token or a user token.")

| Argument      | Example             | Required  | Description
|:---           |:---                 |:---       |:---
| `app`         | `browser_client`    | Required  | The app storing data.
| `requestor`   | `user_345`          | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`          | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true,
    "result": {
      keys: [
        "key1",
        // ...
      ]
    }
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `not_authed`          | No authentication token provided.
| `invalid_auth`        | `requestor` does not have access to `owner` content.
| `invalid_app`         | `app` does not conform to the naming rules.
| `app_not_found`       | `app` does not name an existing app.
| `invalid_user`        | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`      | User specified in `requestor` or user token was not found.
