FORMAT: 1A

# apps.passwords.remove

Removes a password from an existing app. This is used to support password rotation.

:[](common-args.md url:"apps.passwords.remove" token:"Requires a service token.")

| Argument      | Example           | Required  | Description
|:---           |:---               |:---       |:---
| `name`        | `browser_client`  | Required  | The name of the app.
| `password_id` | `ybV3lGh4q1`      | Required  | The password ID to remove.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `app_not_found`           | `name` does not name an existing app.
| `password_not_found`      | `password_id` does not identify a password.
