FORMAT: 1A

# data.cb.merge

Merges new `data` into the existing object stored at the specified `key`.
If no value has been stored, it is implicitly `{}` and the stored value will
be identical to `data`. This method throws an error if there is an existing
stored value which is not an object.

The merge will overwrite any existing properties specified in `data` which
also exist in the value, and will add any properties specified in `data`
which are not present in the existing object. Merge is superficial (not deep).

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"data.cb.merge" token:"Can be used with either a service token or a user token.")

| Argument          | Example           | Required  | Description
|:---               |:---               |:---       |:---
| `key`             | `achievements`    | Required  | The key whose stored value is to be updated.
| `data`            | `{"achievementXYZ": true}`    | Required  | The object which is to be merged with the existing stored value.
| `requestor`       | `user_345`        | Optional  | The user making the request. Required if token type is service token.
| `owner`           | `user_789`        | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `not_authed`              | No authentication token provided.
| `invalid_auth`            | `requestor` does not have access to `owner` content.
| `invalid_key`             | `key` does not conform to the naming rules.
| `invalid_user`            | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`          | Service token used and `requestor` not specified.
| `invalid_data`            | `data` is missing or not a serialized JSON document.
| `invalid_data_type`       | `data` object failed to merge with existing data stored under `key`.
