FORMAT: 1A

# authz.info

Get information on an existing authorization mode.

:[](common-args.md url:"authz.info" token:"Requires a service token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `name`        | `shared_text`             | Required  | The name of the authorization mode.

## Result

```javascript
{
    "ok": true,
    "result": {
        "name": "shared_text",
        "url": "https://example/authz"
    }
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `invalid_name`            | `name` does not conform to the naming rules.
| `authz_not_found`         | `name` does not name an existing authorization mode.
