FORMAT: 1A

# data.user.getShared

Retrieve data for a given user. This method is intended to access data stored by a _different_ user; accessing a user's data on behalf of the user that stored it should use [data.user.get](method-data.user.get.html) instead.

:[](common-args.md url:"data.user.getShared" token:"Requires a user or service token.")

| Argument      | Example           | Required  | Description
|:---           |:---               |:---       |:---
| `id`          | `z3Gh7pQ12z`      | Required  | A unique key to identify the data being stored.
| `requestor`   | `userID`          | Optional  | The user requesting the data (required if a service token is used.)

## Result

```javascript
{
    "ok": true,
    "result": {
        "key":  "annotation_id123",
        "type": "text",
        "data": "data",
    }
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `wrong_token_type`    | This endpoint requires a user token.
| `invalid_share_id`    | `id` does not conform to the naming rules.
| `share_id_not_found`  | `id` does not describe an existing sharing ID for user.
| `forbidden`           | User does not have permission to access shared data.
