FORMAT: 1A

# data.cb.unset

Unsets the value stored at the specified `key`, removing any previously existing value.

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"data.cb.set" token:"Can be used with either a service token or a user token.")

| Argument          | Example           | Required  | Description
|:---               |:---               |:---       |:---
| `key`             | `loginCount`      | Required  | The key whose stored value is to be updated.
| `requestor`       | `user_345`        | Optional  | The user making the request. Required if token type is service token.
| `owner`           | `user_789`        | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `not_authed`              | No authentication token provided.
| `invalid_auth`            | `requestor` does not have access to `owner` content.
| `invalid_key`             | `key` does not conform to the naming rules.
| `invalid_user`            | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`          | User specified in `requestor` or user token was not found.
