FORMAT: 1A

# data.app.merge

Merge a document into an existing one for a given user, as if by an
invocation of [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).
If the existing document is not found, it creates a new one.

:[](common-args.md url:"data.app.merge" token:"Can be used with either a service token or a user token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `key`         | `settings`                | Required  | A unique key to identify the data being stored.
| `data`        | `{"font-weight": "bold"}` | Required  | The serialized JSON document to store.
| `app`         | `browser_client`          | Required  | The app storing data.
| `requestor`   | `user_345`            | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`            | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

Returns the merged object.

```javascript
{
    "ok": true,
    "result": {
        "key":  "settings",
        "data": {
            "font-size": "12pt",
            "font-weight": "bold"
        }
    }
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `invalid_key`         | `key` does not conform to the naming rules.
| `name_in_use`         | `key` is already in use.
| `invalid_data`        | `data` is missing or not a serialized JSON document.
| `invalid_app`         | `app` does not conform to the naming rules.
| `app_not_found`       | `app` does not name an existing app.
| `invalid_user`        | `user` is not a valid user identifier.
| `user_not_found`      | User specified in `user` or user token was not found.
| `forbidden`           | Token is a user token, and user was specified and did not match.
| `quota_exceeded`      | The user does not have sufficient quota to store the data.
