FORMAT: 1A

# data.app.query

Retrieves all documents for a given user that start with a given key prefix

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"data.app.query" token:"Can be used with either a service token or a user token.")

| Argument      | Example               | Required  | Description
|:---           |:---                   |:---       |:---
| `keyPrefix    | `key.prefix`          | Required  | The key prefix string to return all values whose keys start with that prefix.
| `app`         | `browser_client`      | Required  | The app storing data.
| `requestor`   | `user_345`            | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`            | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result
The result is an array of data keys and values stored under any key that
begins with the given `keyPrefix`, for the target `app` and the user
identified by the authentication token or `owner` parameter.

```javascript
{
    "ok": true,
    "result": [
      {
        "app": "browser_client",
        "data": "some value",
        "key": "key.prefix.1",
        "user": "user_789"
      },
      {
        "app": "browser_client",
        "data": 101010101,
        "key": "key.prefix.2",
        "user": "user_789"
      },
    ]
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `not_authed`              | No authentication token provided.
| `invalid_auth`            | `requestor` does not have access to `owner` content.
| `invalid_key`             | `keyPrefix` does not conform to the naming rules.
| `invalid_app`             | `app` does not conform to the naming rules.
| `app_not_found`           | `app` does not name an existing app.
| `invalid_user`            | `owner` or `requestor` is not a valid user identifier.
| `user_not_found`          | User specified in `requestor` or user token was not found.
