FORMAT: 1A

# apps.remove

Unregister an existing authorization mode.

:[](common-args.md url:"apps.remove" token:"Requires a service token.")

| Argument      | Example           | Required  | Description
|:---           |:---               |:---       |:---
| `name`        | `browser_client`  | Required  | The name of the app.
| `force`       | `true`            | Optional  | Remove the app, even if it's being used. Defaults to false.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `app_not_found`           | `name` does not name an existing app.
| `app_in_use`              | The app specified in `name` is being used, and `force` is false.
