FORMAT: 1A

# apps.register

Registers a new app.

Apps will use their name when storing data.

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"apps.register" token:"Requires a service token.")

| Argument          | Example           | Required  | Description
|:---               |:---               |:---       |:---
| `name`            | `browser_client`  | Required  | The name of the app.
| `quota`           | `1024`            | Required  | The storage available to the app per user, in bytes.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `invalid_name`            | `name` does not conform to the naming rules.
| `name_in_use`             | `name` is already used for an existing app.
| `invalid_quota`           | `quota` is not a valid positive integer within max system quota limit.
