FORMAT: 1A

# data.user.get

Retrieve data for a given user.

:[](common-args.md url:"data.user.get" token:"Can be used with either a service token or a user token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `key`         | `annotation_id123`        | Required  | A unique key to identify the data being stored.
| `user`        | `user_345`                | Optional  | The user as which to get the data. Required if token type is service token.

## Result

```javascript
{
    "ok": true,
    "result": {
        "key":  "annotation_id123",
        "type": "text",
        "data": "data"
    }
}
```

## Errors

:[](common-errors.md)

| Error             | Description
|:---               |:---
| `invalid_key`     | `key` does not conform to the naming rules.
| `key_not_found`   | `key` does not describe an existing key for user.
| `invalid_user`    | `user` is not a valid user identifier.
| `user_not_found`  | User specified in `user` or user token was not found.
| `forbidden`       | Token is a user token, and user was specified.
