FORMAT: 1A

# data.app.json.merge

Merge a JSON document into an existing one for a given user, as if by an
invocation of [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).
If the existing document is not found, it creates a new one.

:[](common-args.md url:"data.app.json.merge" token:"Can be used with either a service token or a user token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `key`         | `settings`                | Required  | A unique key to identify the data being stored.
| `data`        | `{"font-weight": "bold"}` | Required  | The serialized JSON document to store.
| `app`         | `browser_client`          | Required  | The app storing data.
| `password`    | `2*HF9H[eQsWSc#k`         | Optional  | The app password. Pass it if token type is user token and the app expects a password.
| `user`        | `user_345`                | Optional  | The user as which to get the data. Required if token type is service token.

## Result

Returns the merged object.

```javascript
{
    "ok": true,
    "result": {
        "key":  "settings",
        "data": {
            "font-size": "12pt",
            "font-weight": "bold"
        }
    }
}
```

## Errors

:[](common-errors.md)

| Error                 | Description
|:---                   |:---
| `invalid_key`         | `key` does not conform to the naming rules.
| `name_in_use`         | `key` is already in use.
| `invalid_data`        | `data` is missing or not a serialized JSON document.
| `invalid_app`         | `app` does not conform to the naming rules.
| `app_not_found`       | `app` does not name an existing app.
| `invalid_password`    | `password` is required but missing.
| `invalid_credentials` | Combination of `app` and `password` is not valid.
| `invalid_user`        | `user` is not a valid user identifier.
| `user_not_found`      | User specified in `user` or user token was not found.
| `forbidden`           | Token is a user token, and user was specified.
| `quota_exceeded`      | The user does not have sufficient quota to store the data.
