FORMAT: 1A

# apps.passwords.add

Adds a password to an existing app. This is used to support password rotation.

:[](common-args.md url:"apps.passwords.add" token:"Requires a service token.")

| Argument      | Example           | Required  | Description
|:---           |:---               |:---       |:---
| `name`        | `browser_client`  | Required  | The name of the app.
| `password`    | `7$R/J*;3.7h*;Er` | Required  | The new password for the app.

## Result

```javascript
{
    "ok": true,
    "result": {
        "id": "ybV3lGh4q1"
    }
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `wrong_token_type`        | This endpoint requires a service token.
| `app_not_found`           | `name` does not name an existing app.
