FORMAT: 1A

# data.cb.decrement

Decrements the numeric value stored at the specified `key`. If no value has been
stored, it is implicitly 0 and the resulting value will be -1. This method throws
an error if there is an existing stored value which is not a number.

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"data.cb.decrement" token:"Can be used with either a service token or a user token.")

| Argument          | Example           | Required  | Description
|:---               |:---               |:---       |:---
| `key`             | `loginCount`      | Required  | The key whose stored value is to be decremented.
| `requestor`   | `user_345`            | Optional  | The user making the request. Required if token type is service token.
| `owner`       | `user_789`            | Optional  | The user whose data is being accessed. Defaults to `requestor` if not specified.

## Result

```javascript
{
    "ok": true
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `invalid_key`             | `key` does not conform to the naming rules.
| `key_not_found`           | `key` does not describe an existing key for user.
| `invalid_user`            | `user` is not a valid user identifier.
| `user_not_found`          | User specified in `user` or user token was not found.
| `invalid_type`            | The value identified by key is not a number and cannot be decremented.
| `forbidden`               | Token is a user token, and user was specified and did not match.
