FORMAT: 1A

# authz.list

List all existing authorization modes.

:[](common-args.md url:"authz.list" token:"Requires a service token.")

## Result

```javascript
{
    "ok": true,
    "result": [
      {
        "name": "shared_text",
        "url": "https://example/authz"
      },
      // ...
    ]
}
```

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `not_authed`              | No authentication token provided.
| `wrong_token_type`        | This endpoint requires a service token.
