FORMAT: 1A

# authz.register

Create and register an authorization mode, which can be used to validate
cross-user access to data.

See [Naming rules](common-names.html) for more information on names.

:[](common-args.md url:"authz.register" token:"Requires a service token.")

| Argument      | Example                   | Required  | Description
|:---           |:---                       |:---       |:---
| `name`        | `shared_text`             | Required  | The name of the authorization mode.
| `url`         | `https://example/authz`   | Required  | The authorization URL.

The authorization URL described by the `url` parameter must be an SSL URL (it
begins with `https`). It must be a `GET` URL, which take the following query
parameters:

| Query parameter   | Example           | Description
|:---               |:---               |:---
| `name`            | `shared_text`     | The name of the authorization mode
| `ctx`             | `id_123`          | Some context passed as a parameter
| `owner`           | `user_abc`        | The ID of the user who owns the data
| `requestor`       | `user_def`        | The ID of the user who is attempting to access the data

The response must be an HTTP 200 when access is allowed, or HTTP 401 when access is denied.

## Errors

:[](common-errors.md)

| Error                     | Description
|:---                       |:---
| `not_authed`              | No authentication token provided.
| `wrong_token_type`        | This endpoint requires a service token.
| `invalid_name`            | `name` does not conform to the naming rules.
| `name_in_use`             | `name` is already used for an existing authorization mode.
| `invalid_url`             | `url` does not conform to a valid URL schema.
